# Generated by Django 5.0.1 on 2024-02-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=100)),
                ('blogImage', models.ImageField(upload_to='')),
                ('blogContent', models.TextField(max_length=10000)),
                ('blogDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=50)),
                ('userAbout', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField(max_length=300)),
                ('commentDate', models.DateTimeField()),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handleBlog.blog')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handleBlog.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handleBlog.customuser'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratingValue', models.FloatField(null=True)),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handleBlog.blog')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handleBlog.customuser')),
            ],
        ),
    ]
