# Generated by Django 5.0.1 on 2024-02-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userpassword',
            new_name='userPassword',
        ),
    ]
