# Generated by Django 5.0.1 on 2024-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0002_rename_userpassword_customuser_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogImage',
            field=models.ImageField(upload_to='handleBlog/images/'),
        ),
    ]
