# Generated by Django 5.0.1 on 2024-02-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0004_alter_blog_blogimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='imageupload',
        ),
    ]
