# Generated by Django 5.0.1 on 2024-02-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0005_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
