# Generated by Django 5.0.1 on 2024-02-19 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0014_alter_blog_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
