# Generated by Django 5.0.1 on 2024-02-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0015_alter_comment_commentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentersName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
