# Generated by Django 5.0.1 on 2024-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0016_comment_commentersname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgetPassToken',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
