# Generated by Django 5.0.2 on 2024-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0018_alter_customuser_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingValue',
            field=models.IntegerField(null=True),
        ),
    ]
