# Generated by Django 5.0.2 on 2024-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0019_alter_rating_ratingvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingValue',
            field=models.IntegerField(default=0),
        ),
    ]
