# Generated by Django 5.0.2 on 2024-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0020_alter_rating_ratingvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
