# Generated by Django 5.0.2 on 2024-03-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0023_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(related_name='followers', to='handleBlog.customuser')),
                ('following', models.ManyToManyField(related_name='following', to='handleBlog.customuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handleBlog.customuser')),
            ],
        ),
    ]
