# Generated by Django 5.0.2 on 2024-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0026_follow_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(to='handleBlog.follow'),
        ),
    ]
