# Generated by Django 5.0.2 on 2024-03-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleBlog', '0027_rename_followers_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='handleBlog.customuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handleBlog.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
